import BarChart from '../../../../components/charts/Bar';
const variabledata = [
  {
    id: 1,
    variableHeading: 'Longitude',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [-124, -122, -120, -118, -116, -114],
      chartData: [-113, -117, -114, -119, -112, -123],
      min: -124.25,
      max: -114.31,
      stepSize: 10,
    },
  },
  {
    id: 2,
    variableHeading: 'Latitude',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [34, 36, 38, 40, 42],
      chartData: [35, 39, 37, 34, 42],
      min: 32.54,
      max: 41.95,
      stepSize: 0,
    },
  },
  {
    id: 3,
    variableHeading: 'housing_mediam_age',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 10, 20, 30, 40, 50],
      chartData: [12, 36, 21, 49, 11],
      min: 1,
      max: 52,
      stepSize: 3,
    },
  },
  {
    id: 4,
    variableHeading: 'total_rooms',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 10000, 20000, 30000, 40000, 50000],
      chartData: [48000, 12000, 25000, 11000, 33000, 17000],
      min: 2,
      max: 39320,
      stepSize: 3000,
    },
  },
  {
    id: 5,
    variableHeading: 'total_bedrooms',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 2000, 4000, 6000],
      chartData: [500, 2000, 1300, 4000, 5500, 1000],
      min: 1,
      max: 6645,
      stepSize: 200,
    },
  },
  {
    id: 6,
    variableHeading: 'Population',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 10000, 20000, 30000],
      chartData: [29000, 12000, 8000, 21000, 18000, 27000],
      min: 3,
      max: 35682,
      stepSize: 2000,
    },
  },
  {
    id: 7,
    variableHeading: 'households',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 2000, 4000, 6000],
      chartData: [5000, 1300, 3000, 6000, 5500, 3000],
      min: 1,
      max: 6082,
      stepSize: 500,
    },
  },
  {
    id: 8,
    variableHeading: 'median_income',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 12928 },
      { dataHeading: 'Distinct(%)', value: '62.6%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: 3.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 5, 10, 15],
      chartData: [3, 15, 11, 7],
      min: 0.4999,
      max: 15.0001,
      stepSize: 1,
    },
  },
  {
    id: 9,
    variableHeading: 'median_house_value',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 3842 },
      { dataHeading: 'Distinct(%)', value: '18.6%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: 206855.82 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 14999 },
      { dataHeading: 'Maximum', value: 500001 },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: '161.4KiB' },
    ],
    chartData: {
      chartType: 'Bar',
      chartlabels: [0, 100000, 200000, 300000, 400000, 500000],
      chartData: [120000, 400000, 300000, 250000, 490000, 240000],
      min: 14999,
      max: 500001,
      stepSize: 50000,
    },
  },
  {
    id: 10,
    variableHeading: 'ocean_proximity',
    variableScondaryHeading: 'Boolean',
    intialTableData: [
      { dataHeading: 'Distinct', value: 2 },
      { dataHeading: 'Distinct(%)', value: '<0.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Memorysize', value: '20.3 KiB' },
    ],
    // secondaryTableData: [
    //   { dataHeading: 'Minimum', value: 844 },
    //   { dataHeading: 'Maximum', value: '4.1%' },
    //   { dataHeading: 'Missing', value: 0 },
    //   { dataHeading: 'Missing(%)', value: '0.0%' },
    //   { dataHeading: 'Zeros', value: 0 },
    //   { dataHeading: 'Infinite(%)', value: '0.0%' },
    //   { dataHeading: 'Mean', value: -119.5697 },
    // ],
    chartData: {
      chartType: 'horizontal',
      chartlabels: ['False', 'True'],
      chartData: [18350, 2290],
    },
  },
  {
    id: 10,
    variableHeading: 'ocean_proximity',
    variableScondaryHeading: 'Categorical',
    intialTableData: [
      { dataHeading: 'Distinct', value: 5 },
      { dataHeading: 'Distinct(%)', value: '<0.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Memorysize', value: '161.4 KiB' },
    ],
    // secondaryTableData: [
    //   { dataHeading: 'Minimum', value: 844 },
    //   { dataHeading: 'Maximum', value: '4.1%' },
    //   { dataHeading: 'Missing', value: 0 },
    //   { dataHeading: 'Missing(%)', value: '0.0%' },
    //   { dataHeading: 'Zeros', value: 0 },
    //   { dataHeading: 'Infinite(%)', value: '0.0%' },
    //   { dataHeading: 'Mean', value: -119.5697 },
    // ],
    chartData: {
      chartType: 'horizontal',
      chartlabels: ['<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'NEAR BAY', ''],
      chartData: [9136, 6551, 2658, 2290, 5],
    },
  },
];

export default variabledata;
