import BarChart from '../../../../components/charts/Bar';
const variabledata = [
  {
    id: 1,
    variableHeading: 'Longitude',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
  },
  {
    id: 2,
    variableHeading: 'Latitude',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
  },
  {
    id: 3,
    variableHeading: 'housing_mediam_age',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
  },
  {
    id: 4,
    variableHeading: 'total_rooms',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
  },
  {
    id: 5,
    variableHeading: 'Population',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
  },
  {
    id: 6,
    variableHeading: 'households',
    variableScondaryHeading: 'Real number (R) ',
    intialTableData: [
      { dataHeading: 'Distinct', value: 844 },
      { dataHeading: 'Distinct(%)', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Infinite', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
    secondaryTableData: [
      { dataHeading: 'Minimum', value: 844 },
      { dataHeading: 'Maximum', value: '4.1%' },
      { dataHeading: 'Missing', value: 0 },
      { dataHeading: 'Missing(%)', value: '0.0%' },
      { dataHeading: 'Zeros', value: 0 },
      { dataHeading: 'Infinite(%)', value: '0.0%' },
      { dataHeading: 'Mean', value: -119.5697 },
    ],
  },
];

export default variabledata;
